### ISSUE TITLE
PyPI does not allow direct dependencies

### ISSUE THREAD

**Issue by dgerlanc** [AmpersandTV/pymc3-hmm#38]
PyPI does not support `git` entries in `install_requires`.

```bash
make pypi
```

```bash
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pymc3_hmm-0.0.1-py2-none-any.whl
100%|█| 20.3k/20.3k [00:00<00:00, 60.3kB/s]NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'pymc3 @ git+https://github.com/pymc-devs/pymc3@master'
make: *** [pypi] Error 1
```

**Please provide any additional information below.**

## Versions and main components
* Python version: 3.8.6
* Operating system: OS X
* How did you install Theano: pip

**Comment by rlouf** [comment]
Have you tried using the `dependency_links` keyword argument to `setup()`? [Doc](https://setuptools.readthedocs.io/en/latest/userguide/keywords.html). You can specify the address to the tarball and add the package's name and version in `install_requires`.

I believe that you can also do `pip instal git+<https://adress_to_repo.git>` in the terminal.

**Comment by dgerlanc** [comment]
> Have you tried using the `dependency_links` keyword argument to `setup()`? [Doc](https://setuptools.readthedocs.io/en/latest/userguide/keywords.html). You can specify the address to the tarball and add the package's name and version in `install_requires`.

Have not - will see if we can just pin to `master` branch `.tar.gz` that Github automatically creates.

**Comment by brandonwillard** [comment]
Ah, yeah, [this](https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi) implies that it's possible, as well.

**Comment by brandonwillard** [comment]
Unfortunately, it doesn't look like `dependency_links` will work as expected; at some point, `pip` apparently shuts it down (see https://github.com/pypa/pip/issues/6162 and https://github.com/pypa/pip/issues/5898).
