### ISSUE TITLE
Set up Python packaging

### ISSUE THREAD

**Issue by brandonwillard** [AmpersandTV/pymc3-hmm#5]
We need to set up a PyPi account to host this Python package; otherwise, we won't be able to add it as a proper dependency in another package's `setup.py`.

**Comment by brandonwillard** [comment]
PyMC3 published a [new release](https://github.com/pymc-devs/pymc3/releases/tag/v3.10.0), so we can change our dependencies and put this on PyPI now.

**Comment by dgerlanc** [comment]
Are we set on this?
